- name: install desktop tools
  become: yes
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
      - gparted
      - meld
      - shutter
      - unity-tweak-tool
      - vlc
      - ubuntu-restricted-extras
      - bleachbit
