---
# tasks file for vagrant

- name: Ensure vagrant exists
  sudo: yes
  action: "{{ ansible_pkg_mgr }} name=vagrant state=present"

- name: Ensure vagrant plugins exists
  shell: vagrant plugin install {{ item }}
  with_items:
    - vagrant-lxc
    - vagrant-cachier
    - vagrant-vbguest
