---
# tasks file for vagrant

- name: Ensure vagrant exists
  become: yes
  action: "{{ ansible_pkg_mgr }} name=vagrant state=present"

- name: Ensure vagrant plugins exists
  command: vagrant plugin install {{ item }}
  when: false
  with_items:
    - vagrant-lxc
    - vagrant-cachier
    - vagrant-vbguest
