---
# tasks file for apt
# see http://docs.ansible.com/ansible/apt_module.html
#
- name: install apt-file
  become: yes
  apt: name=apt-file state=present

- name: update apt-file db
  become: yes
  command: apt-file update
  when: false

- name: create apt symlink
  file: src={{ playbook_dir }}/roles/pkg/files/apt.sh dest=~/.bash.d/apt.sh state=link
