---
# tasks file for redhat / dnf

- name: Ensure DNF aliases available for all users
  become: yes
  copy: src={{ playbook_dir }}/roles/pkg/files/dnf.sh dest=/etc/profile.d/dnf.sh
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 22
