---
# tasks file for yum/dnf

- name: install yum-utils
  sudo: yes
  action: "{{ ansible_pkg_mgr }} name=yum-utils state=present"

- name: create yum symlink
  file: src={{ playbook_dir }}/roles/pkg/files/yum.sh dest=~/.bash.d/yum.sh state=link

- name: create dnf symlink
  file: src={{ playbook_dir }}/roles/pkg/files/dnf.sh dest=~/.bash.d/dnf.sh state=link
