---
# tasks file for redhat
# @see http://docs.ansible.com/ansible/user_module.html
# @see http://docs.ansible.com/ansible/group_module.html

- include: redhat_yum.yml
  when: ansible_pkg_mgr == "yum"

- include: redhat_dnf.yml
  when: ansible_pkg_mgr == "dnf"
