---
# tasks file for redhat / yum

- name: Install yum-utils
  become: yes
  action: "{{ ansible_pkg_mgr }} name=yum-utils state=present"

- name: Ensure YUM aliases available for all users
  become: yes
  copy: src={{ playbook_dir }}/roles/pkg/files/yum.sh dest=/etc/profile.d/yum.sh
