---
# tasks file for xclip

- name: install xclip
  action: "{{ ansible_pkg_mgr }} name=xclip state=present"

- name: create symlink
  file: src={{ playbook_dir }}/roles/xclip/files/xclip.sh dest=~/.bash.d/xclip.sh state=link
