---
# tasks file for python - redhat

- name: install python and related packages
  sudo: yes
  yum: pkg={{item}} state=present
  with_items:
    - python-virtualenv 
    - python-virtualenvwrapper
    - python-flake8
