---
# tasks file for monitoring

- name: install monitoring tools
  become: yes
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
      - htop
      - lm-sensors
      - hddtemp
