---
# tasks file for powertop
# @see http://superuser.com/a/877796
# @see https://technet.microsoft.com/en-us/library/ee156537.aspx

- name: detect machine chassis type
  become: yes
  command: dmidecode --string chassis-type
  register: chassis_type
  changed_when: False

# todo: test this in others gnu/linux distros
# - debug: var=chassis_type

- name: install powertop
  become: yes
  action: "{{ ansible_pkg_mgr }} name=powertop state=present"
  when: chassis_type.stdout|lower == 'notebook'

- name: install tlp
  become: yes
  action: "{{ ansible_pkg_mgr }} name={{item}} state=present"
  with_items:
    - tlp
    - tlp-rdw
  when: chassis_type.stdout|lower == 'notebook'

- name: start tlp
  become: yes
  service: name=tlp state=restarted
  when: chassis_type.stdout|lower == 'notebook'
