---
# tasks file for chrome
# see https://www.google.com/linuxrepositories/

- name: add chrome repository
  command: cp {{ playbook_dir }}/roles/chrome/files/google-chrome.repo /etc/yum.repos.d/google-chrome.repo
  sudo: yes

- name: install google chrome stable
  action: "{{ ansible_pkg_mgr }} name=google-chrome-stable state=present"
  sudo: yes

