---
# tasks file for chrome
# @see https://www.google.com/linuxrepositories/

- name: add repository
  command: cp {{ playbook_dir }}/roles/chrome/files/google-chrome.repo /etc/yum.repos.d/google-chrome.repo
  become: yes
  changed_when: False

- name: install chrome stable
  action: "{{ ansible_pkg_mgr }} name=google-chrome-stable state=present"
  become: yes
