---
# tasks file for z

# msg: Aborting, target uses selinux but python bindings (libselinux-python)
# aren't installed!
- name: install libselinux-python
  action: "{{ ansible_pkg_mgr }} name=libselinux-python state=present"
  sudo: yes
  when: ansible_distribution == "Fedora"

- name: clone z repository 
  git: repo=https://github.com/rupa/z.git dest=/tmp/z

- name: add z.sh to my customized bash
  copy: src=/tmp/z/z.sh dest=~/.bash.d/z.sh

- name: install the z.sh man page
  sudo: yes
  copy: src=/tmp/z/z.1 dest=/usr/local/man/man1/z.1
  when: ansible_os_family == "Debian"

- name: install the z.sh man page
  sudo: yes
  copy: src=/tmp/z/z.1 dest=/usr/local/share/man/man1/z.1
  when: ansible_os_family == "Debian"

- name: clean up local repository
  file: path=/tmp/z state=absent
