---
# tasks file for virtualbox

- name: Download VirtualBox Fedora repo file
  sudo: yes
  get_url: >
      url=http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo 
      dest=/etc/yum.repos.d/virtualbox.repo
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 22

- name: Ensure VirtualBox exists
  sudo: yes
  action: "{{ ansible_pkg_mgr }} name={{item}} state=present"
  with_items:
      - VirtualBox-5.0
      - VirtualBox-guest
      - kernel-devel # to recompile VirtualBox kernel module, see next task
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 22

  # @see http://www.webupd8.org/2015/10/workaround-for-sbinvboxconfig-not.html
- name: Ensure VirtualBox kernel module exists
  sudo: yes
  shell: sudo /sbin/rcvboxdrv setup
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 22
