---
# tasks file for sphinx

- name: install plantuml (fedora)
  sudo: yes
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
      - plantuml
      - java-1.8.0-openjdk
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 23

- name: install sphinx and plugins
  sudo: yes
  pip: name={{ item }}
  with_items:
      - sphinx
      - sphinx_rtd_theme
      - sphinx-autobuild
      - sphinxcontrib-plantuml
