---
# tasks file for tmux

- name: install tmux
  action: "{{ ansible_pkg_mgr }} name=tmux state=present"

- name: create symlink
  file: src={{ playbook_dir }}/roles/tmux/files/.tmux.conf  dest=~/.tmux.conf state=link
