---
# tasks file for common

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: centos.yml
  when: ansible_distribution == "CentOS"

- include: fedora.yml
  when: ansible_distribution == "Fedora"
