---
# tasks file for screen

- name: install screen
  action: "{{ ansible_pkg_mgr }} name=screen state=present"
  sudo: yes

- name: create symlink
  file: src={{ playbook_dir }}/roles/screen/files/.screenrc  dest=~/.screenrc state=link
