---
# tasks file for dnsmasq
# @see http://docs.ansible.com/ansible/service_module.html
# @see http://askubuntu.com/a/233224
# @see https://icann.org/namecollision

- name: add .dev tld to dnsmasq
  become: yes
  lineinfile:
    line: address=/dev/127.0.0.1
    create: yes
    state: present
    dest: /etc/NetworkManager/dnsmasq.d/tld.dev

- name: restart network-manager
  become: yes
  service: name=network-manager state=restarted
  when: ansible_os_family == "Debian"

- name: restart network-manager
  become: yes
  service: name=NetworkManager state=restarted
  when: ansible_os_family == "RedHat"

- name: wait for network-manager to complete restart
  pause: seconds=10
