---
# tasks file for perl

- name: install perl and its related packages
  become: yes
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
      - perl
      - cpanminus

- name: install necessary perl packages
  become: yes
  cpanm: name={{ item }}
         installdeps=True
  with_items:
      - Perl::Critic
      - Data::Dumper::Simple
      - Pod::Text::Color

- name: create perl aliases symlink
  file: src={{ playbook_dir }}/roles/perl/files/perl.sh  dest=~/.bash.d/perl.sh state=link
