# installation

- name: add docker key
  become: yes
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: add docker repository
  become: yes
  lineinfile: >
      dest=/etc/apt/sources.list.d/docker.list state=present create=yes
      line="deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"

- name: install docker
  become: yes
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
      - docker.io
      - apt-transport-https
      - ca-certificates
      - docker-compose
