---
# tasks file for php

- name: install php (fedora)
  become: yes
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
      - php-cli
      - php-pear
      - phpunit
      - composer
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 22
