---
# tasks file for vim

- name: install vim and related packages
  sudo: yes
  action: "{{ ansible_pkg_mgr }} name={{item}} state=present"
  with_items:
      - pylint
      - php-pear
      - exuberant-ctags

- name: create symlink
  file: src={{ playbook_dir }}/roles/vim/files/.vimrc  dest=~/.vimrc state=link

- name: install vim bundles
  command: vim +BundleInstall +qall
